### ISSUE TITLE
Set biodocker.org domain for BioDocker.github.io

### ISSUE THREAD

**Issue by rajido** [BioDocker/BioDocker.github.io#1]
After a chat with Yasset we decided to purchase biodocker.org. Though we could get some hosting for the website by now seems easier to have the main site hosted in github pages.

**Comment by Leprevost** [comment]
I can host a static website on Amazon, it will cost something around a $1 per month.

**Comment by rajido** [comment]
That's OK. But I do not see the need to create a dependency on Amazon specially when in gitHub is 0$. I vote for code and site page in the same place with the option to improve the main site with pull requests. We should aim to get something like ... http://biojs.net (hosted as well in gitHub ... https://github.com/biojs/biojs.net)

**Comment by ypriverol** [comment]
Agree with @rajido

**Comment by Leprevost** [comment]
yea, I also think that having all together is much better
